// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Carrega .env.local se existir (sobrescreve .env)
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Volta a usar o Postgres do Supabase (DIRECT_URL ou DATABASE_URL).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
