// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Carrega .env.local se existir (sobrescreve .env)
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma 7 usa só uma URL. Para migrations, use DIRECT_URL se existir (Session pooler 5432);
  // para o app, use DATABASE_URL (Transaction pooler 6543). Aqui o CLI usa DIRECT_URL para migrate.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
